### ISSUE TITLE
Does this code work with the current Kucoin REST API?

### ISSUE THREAD

**Issue by unixneo** [mwlang/kucoin-api#1]
Does this code work with the current Kucoin REST API?

The reason I ask is your README says "no signatures required; but the API docs say:

> Creating a Request
> All private REST requests must contain the following headers:

> KC-API-KEY The API key as a string.
> KC-API-SIGN The base64-encoded signature (see Signing a Message).
> KC-API-TIMESTAMP A timestamp for your request.
> KC-API-PASSPHRASE The passphrase you specified when creating the API key.
> KC-API-KEY-VERSION You can check the version of API key on the page of [API Management](https://www.kucoin.com/account/api)

Reference:

https://docs.kucoin.com/#authentication

**Comment by tkling** [comment]
@unixneo Yes, it works. See here - this gem's Faraday auth middleware handles setting the signature in headers https://github.com/mwlang/kucoin-api/blob/master/lib/kucoin/api/middleware/auth_request.rb#L18

I have a feeling the README wording is meant to communicate "users of this gem do not need to handle generating signatures manually" :)
